apiVersion: v1
kind: Service
metadata:
  name: lms
  labels:
    app: lms
    type: flask
spec:
  type: NodePort
  ports:
    - targetPort: 5000
      port: 80
      nodePort: 30080
  selector:
    app: lms
    type: flask
