apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: lms
    type: flask
spec:
  type: ClusterIP
  ports:
    - targetPort: 3306
      port: 3306
  selector:
    app: lms
    type: flask
